---
# tasks file for prometheus
- name: Install Prometheus
  apt:
    name: prometheus
    update_cache: yes
    state: latest
- name: Prometheus Config 1
  template:
    src: prometheus.j2
    dest: /etc/default/prometheus
    group: root
    owner: root
    mode: 0644
  notify: restart_prometheus
- name: Prometheus Config 2
  template:
    src: prometheus.yml.j2
    dest: '{{ prometheus_dir_configuration }}/prometheus.yml'
    group: prometheus
    owner: prometheus
    mode: 0755
  notify: reload_prometheus
  

