---
# tasks file for ansible_dir/roles/docker-swarm/
- name: check/init swarm
  docker_swarm:
    state: present
    advertise_addr: eth1
  register: __output_swarm
  when: inventory_hostname in groups['managers'][0]

- name: install worker
  docker_swarm:
    state: join
    timeout: 60
    advertise_addr: eth1
    join_token: "{{ hostvars[groups['managers'][0]]['__output_swarm']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: "{{ groups['managers'][0] }}"
  when: inventory_hostname in groups['workers']





# - name: Copy 
#   copy:
#     src: /home/omar/ansible/ansible_dir/docker
#     dest: /tmp/
# - name: Build First Test Images
#   docker_image:
#     name: myimage
#     build:
#       path: /tmp/docker
#     source: build
# - name: Create a data container
#   docker_container:
#     name: mydata
#     image: busybox
#     volumes:
#       - /data
