---
# tasks file for roles/nfs-client

- name: Install NFS packages
  apt:
    name: nfs-common
    state: present
    update_cache: yes
- name: Create NFS Directory
  file:
    path: "/mnt/{{ item }}"
    state: directory
    owner: root
    group: root
  with_items: 
  - "{{ mount_paths }}"
- name: Mount an NFS volume
  mount:
    src: "{{ groups['nfs'][0] }}:{{ mount_directory }}/{{ item }}"
    path: /mnt/{{ item }}
    opts: rw
    state: mounted
    fstype: nfs
  with_items: "{{ mount_paths }}"
