---
# tasks file for roles/build_docker_targets
- name: install docker for python3
  apt:
      name: python3-docker
      state: present

- name: Start Target Containers
  docker_container:
    name: "{{ lookup('env', 'USER') | default('omar', True) }}-target-{{ item }}"
    image: priximmo/buster-systemd-ssh
    state: started
    privileged: yes
    published_ports: all
    hostname: "{{ lookup('env', 'USER') | default('omar', True) }}-target-{{ item }}"
    volumes:
     - /srv/data:/srv/html
     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  with_sequence: count='{{ number_machine }}'
- name: Add Containers to Docker group
  add_host:
    name:  "{{ lookup('env', 'USER') | default('omar', True) }}-target-{{ item }}"
    ansible_connection: docker
    groups: docker
  with_sequence: count='{{ number_machine }}'

- name: Run a simple command (command)
  community.docker.docker_container_exec:
    container: "{{ item }}"
    argv:
      - /bin/bash
      - "-c"
      -  "
      useradd -m -p sa3tHJ3/KuYvI --shell /bin/bash {{ lookup('env', 'USER') | default('omar', True) }} &&\
      mkdir -p  {{ lookup('env', 'HOME') }}/.ssh && \
      chmod 700 {{ lookup('env', 'HOME') }}/.ssh && \
      chown {{ lookup('env', 'USER') | default('omar', True) }}:{{ lookup('env', 'USER') | default('omar', True) }} {{ lookup('env', 'HOME') }}/.ssh && \
      echo '{{ lookup('env', 'USER') | default('omar', True) }}   ALL=(ALL) NOPASSWD: ALL'>>/etc/sudoers && \
      echo '{{ sshkey_file }}' >{{ lookup('env', 'HOME') }}/.ssh/authorized_keys && \
      service sshd start
      "
  with_items: "{{ groups['docker'] }}"
  register: result
- debug:
    var: result

